[package]
name = "reversi-ai"
authors = ["curegit"]
version = "1.0.1"
edition = "2024"
license = "Apache-2.0"
readme = "README.md"
publish = false

[lib]
crate-type = ["rlib", "cdylib"]
doctest = false

[dependencies]
num_cpus = "1.16.0"
